Smarties2: abstraction.c File Reference
abstraction.c File Reference
#include "abstraction.h"
#include "system.h"
#include <math.h>
Functions
void motor_stuff ()
Takes controll over the catcher and revolver stepper engines.
void rotary_encoder_stuff ()
Takes controll over the rotary encoder (user input) device.
void lightbarrier_stuff ()
Take control over the lightbarriers.
void sensor_tcs_stuff ()
Takes control over the TCS color sensor.
void vibrator_stuff ()
Takes control over the shaker (vibrator) device.
Detailed Description
All these functions are expected to be called every millisecond by the function ISR (TIMER0_OVF_vect) in the file my_interrupt.c
Definition in file abstraction.c.
Function Documentation
void lightbarrier_stuff ()
Take control over the lightbarriers.
This function is expected to be called regulary. It polls the input pins of the lightbarrier and sets the corresponding flags of lightbarrier struct. This function assumes that lightbarriers are always enabled.
Definition at line 236 of file abstraction.c.
References IS_LB_CATCHER, IS_LB_REVOLVER, lb_blocked, smartie_sorter_t::lb_catcher, lb_free, smartie_sorter_t::lb_revolver, lightbarrier_t::passes, lightbarrier_t::status, and lightbarrier_t::status_last.
Referenced by ISR().
void motor_stuff ()
Takes controll over the catcher and revolver stepper engines.
The ramp up is made by linear shrinking the time period t for each step:
  Steps
  ^
  |         4t                 3t       2t   t  t  t  t
  *                       *           *     *  *  *  *  *
  |
  +--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-> Time
  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18
 Symbolic diagram, no real values
This function is expected to be called every millisecond to work properly.
Important setting values are:
CATCH_STEP_DURATION
CATCH_RAMP_DURATION
REV_STEP_DURATION
REV_RAMP_DURATION
Definition at line 68 of file abstraction.c.
References smartie_sorter_t::mot_catcher, and smartie_sorter_t::mot_revolver.
Referenced by ISR().
void rotary_encoder_stuff ()
Takes controll over the rotary encoder (user input) device.
This function is expected to be called regulary. It polls the input pins for the rotary encoder and sets the corresponding flags of the rotary_encoder struct.
Definition at line 170 of file abstraction.c.
References IS_ROTENC_A, IS_ROTENC_AB, IS_ROTENC_B, IS_ROTENC_NONE, IS_ROTENC_PUSH, rotary_encoder_t::left, rotary_encoder_t::push, rotary_encoder_t::pushtmp, rotary_encoder_t::right, smartie_sorter_t::rotenc, ROTENC_A, ROTENC_B, ROTENC_BOTH, ROTENC_NONE, ROTENC_PUSH, and rotary_encoder_t::rottmp.
Referenced by ISR().
void sensor_tcs_stuff ()
Takes control over the TCS color sensor.
This function is expected to be called exectly every millisecond to work properly. This function will read the current color of the smartie.
About the way of color detection please refere to the Main page
Definition at line 283 of file abstraction.c.
References col_blue, col_green, col_red, COL_SENS_TCS_DISABLE, COL_SENS_TCS_ENABLE, COL_SENS_TCS_FREQ_MESURE_DI, COL_SENS_TCS_FREQ_MESURE_EN, COL_SENS_TCS_SAMPLE_TIME, COL_SENS_TCS_SET_FILTER, col_unknown, color_sensor_tcs_t::color, color_sensor_tcs_t::distance, color_sensor_tcs_t::filter_freq_blue, color_sensor_tcs_t::filter_freq_green, color_sensor_tcs_t::filter_freq_none, color_sensor_tcs_t::filter_freq_red, smartie_sorter_t::sens_tcs, color_sensor_tcs_t::slopes, stat_finished, stat_idle, stat_start_working, stat_stop_working, stat_working, color_sensor_tcs_t::status, color_sensor_tcs_t::status_last, and color_sensor_tcs_t::time.
Referenced by ISR().
void vibrator_stuff ()
Takes control over the shaker (vibrator) device.
This function is expected to be called regulary. It polls the input pins of the shaker and sets the corresponding flags of the shaker struct. This function assumes that
Definition at line 428 of file abstraction.c.
References vibrator_t::duration, stat_finished, stat_idle, stat_start_working, stat_stop_working, stat_working, vibrator_t::status, vibrator_t::status_last, smartie_sorter_t::vibr, VIBR_DURATION, VIBR_OFF, and VIBR_ON.
Referenced by ISR().