Smarties2: inits.c File Reference
inits.c File Reference
Some init functions.
#include "smarties2.h"
#include "lcd_display.h"
#include "inits.h"
#include "system.h"
#include "menu.h"
#include "ee.h"
Functions
void init_all ()
Calls all necessary init functions.
void init_io ()
Configures nearly all General IO pins, disables JTAG.
void init_sensor_tcs ()
Set up the TCS color sensor.
void init_timer ()
This will generate an Interrupt every millisecond by Timer 0 on compare match.
void init_memory ()
Inits important system variables, also from EEprom.
void init_motors ()
Brings revolver and catcher to defined positions; Set up important motor values.
void init_menu ()
Creates the menu stucture, connects menus, connects functions to menus.
Detailed Description
Some init functions.
Copyright (c) 2008 Simeon Felis
Definition in file inits.c.
Function Documentation
void init_menu ()
Creates the menu stucture, connects menus, connects functions to menus.
The menu structure and functionality is explained in menu.h in detailed.
Definition at line 228 of file inits.c.
References menu_entry_t::function, menu_entry_t::l_action, menu_entry_t::next, menu_entry_t::prev, menu_entry_t::r_action, menu_entry_t::submenu, sys_catcher_rotate(), sys_enter_submenu(), sys_enter_topmenu(), sys_measure_tcs(), sys_pause(), sys_reference_measure_blue(), sys_reference_measure_brown(), sys_reference_measure_green(), sys_reference_measure_orange(), sys_reference_measure_pink(), sys_reference_measure_purple(), sys_reference_measure_red(), sys_reference_measure_restore(), sys_reference_measure_yellow(), sys_resume(), sys_revolver_rotate(), sys_speed_down(), sys_speed_up(), menu_entry_t::text, and menu_entry_t::topmenu.
Referenced by init_all().
void init_timer ()
This will generate an Interrupt every millisecond by Timer 0 on compare match.
The interrupt settings are related like following:
There is an error of about 0.8% from 1 Millisecond
Definition at line 123 of file inits.c.
Referenced by init_all().