Smarties2: lcd_display.c File Reference
lcd_display.c File Reference
#include <inttypes.h>
#include <avr/io.h>
#include <util/delay.h>
#include <avr/pgmspace.h>
#include "lcd_display.h"
Functions
void lcd_command (uint8_t cmd)
Send LCD controller instruction command.
void lcd_data (uint8_t data)
Send data byte to LCD controller.
void lcd_gotoxy (uint8_t x, uint8_t y)
Set cursor to specified position.
void lcd_clrscr (void)
Clear display and set cursor to home position.
void lcd_home (void)
Set cursor to home position.
void lcd_putc (char c)
Display character at current cursor position.
void lcd_puts (const char *s)
Display string without auto linefeed.
void lcd_puts_p (const char *progmem_s)
Display string from program memory without auto linefeed.
void lcd_init (uint8_t dispAttr)
Initialize display and select type of cursor.
Detailed Description
Title : HD44780U LCD library Author: Peter Fleury <pfleury@gmx.ch> http://jump.to/fleury File:
Id
lcd.c,v 1.14.2.1 2006/01/29 12:16:41 peter Exp
Software: AVR-GCC 3.3 Target: any AVR device, memory mapped mode only for AT90S4414/8515/Mega
DESCRIPTION Basic routines for interfacing a HD44780U-based text lcd display
Originally based on Volker Oth's lcd library, changed lcd_init(), added additional constants for lcd_command(), added 4-bit I/O mode, improved and optimized code.
Library can be operated in memory mapped mode (LCD_IO_MODE=0) or in 4-bit IO port mode (LCD_IO_MODE=1). 8-bit IO port mode not supported.
Memory mapped mode compatible with Kanda STK200, but supports also generation of R/W signal through A8 address line.
USAGE See the C include lcd.h file for a description of each function
Definition in file lcd_display.c.
Function Documentation
void lcd_clrscr (void)
Clear display and set cursor to home position.
Parameters:
void
Returns:
none
Definition at line 434 of file lcd_display.c.
References lcd_command().
Referenced by init_all(), lcd_init(), and main().
void lcd_command (uint8_t cmd)
Send LCD controller instruction command.
Parameters:
cmd instruction to send to LCD controller, see HD44780 data sheet
Returns:
none
Definition at line 372 of file lcd_display.c.
Referenced by lcd_clrscr(), lcd_gotoxy(), lcd_home(), and lcd_init().
void lcd_data (uint8_t data)
Send data byte to LCD controller.
Similar to lcd_putc(), but without interpreting LF
Parameters:
data byte to send to LCD controller, see HD44780 data sheet
Returns:
none
Definition at line 384 of file lcd_display.c.
void lcd_gotoxy (uint8_t x, uint8_t y)
Set cursor to specified position.
Parameters:
x horizontal position
(0: left most position)
y vertical position
(0: first line)
Returns:
none
Definition at line 398 of file lcd_display.c.
References lcd_command(), LCD_START_LINE1, LCD_START_LINE2, LCD_START_LINE3, and LCD_START_LINE4.
Referenced by main().
void lcd_home (void)
Set cursor to home position.
Parameters:
void
Returns:
none
Definition at line 443 of file lcd_display.c.
References lcd_command().
void lcd_init (uint8_t dispAttr)
Initialize display and select type of cursor.
Parameters:
dispAttr LCD_DISP_OFF display off
LCD_DISP_ON display on, cursor off
LCD_DISP_ON_CURSOR display on, cursor on
LCD_DISP_ON_CURSOR_BLINK display on, cursor on flashing
Returns:
none
Definition at line 538 of file lcd_display.c.
References lcd_clrscr(), lcd_command(), LCD_DATA0_PIN, LCD_DATA0_PORT, LCD_DATA1_PIN, LCD_DATA1_PORT, LCD_DATA2_PIN, LCD_DATA2_PORT, LCD_DATA3_PIN, LCD_DATA3_PORT, LCD_E_PIN, LCD_E_PORT, LCD_RS_PIN, LCD_RS_PORT, LCD_RW_PIN, and LCD_RW_PORT.
Referenced by init_all().
void lcd_putc (char c)
Display character at current cursor position.
Parameters:
c character to be displayed
Returns:
none
Definition at line 454 of file lcd_display.c.
References LCD_DISP_LENGTH, LCD_START_LINE1, LCD_START_LINE2, LCD_START_LINE3, and LCD_START_LINE4.
Referenced by lcd_puts(), and lcd_puts_p().
void lcd_puts (const char * s)
Display string without auto linefeed.
Parameters:
s string to be displayed
Returns:
none
Definition at line 501 of file lcd_display.c.
References lcd_putc().
Referenced by init_all(), main(), and smartie_lcd_write_color().
void lcd_puts_p (const char * progmem_s)
Display string from program memory without auto linefeed.
Parameters:
s string from program memory be be displayed
Returns:
none
See also:
lcd_puts_P
Definition at line 518 of file lcd_display.c.
References lcd_putc().