Smarties2: smarties2.c File Reference
smarties2.c File Reference
Entry file for Smarties project.
#include <avr/interrupt.h>
#include <stdlib.h>
#include "smarties2.h"
#include "system.h"
#include "inits.h"
#include "menu.h"
#include "ee.h"
#include "lcd_display.h"
Functions
void smartie_lcd_write_color (smartie_color color)
Writes the color to the current postion of the display.
int main (void)
Entry functin for smarties2.
Detailed Description
Entry file for Smarties project.
Copyright (c) 2008 Simeon Felis
Version:
0.1
Definition in file smarties2.c.
Function Documentation
int main (void)
Entry functin for smarties2.
This function controls the whole smarties machine by checking the current mode and performing the single steps required for the mode.
This function also handles the user inputs.
The subfunctions for driving the periphals are collected in system.h. The LCD menu is controlled by functions collected in lcd_display.h.
Definition at line 221 of file smarties2.c.
References catcher_rotate_absolute(), col_blue, col_brown, col_green, col_orange, col_pink, col_purple, col_red, col_yellow, smartie_t::color, color_sensor_tcs_t::color, stepper_motor_t::current_pos, ee_memory_t::def_blu, ee_memory_t::def_gre, ee_memory_t::def_red, color_sensor_tcs_t::distance, color_sensor_tcs_t::filter_freq_blue, color_sensor_tcs_t::filter_freq_green, color_sensor_tcs_t::filter_freq_none, color_sensor_tcs_t::filter_freq_red, system_step_t::I, system_step_t::II, system_step_t::III, init_all(), menu_entry_t::l_action, smartie_sorter_t::lb_revolver, lcd_clrscr(), lcd_gotoxy(), lcd_puts(), rotary_encoder_t::left, system_state_t::mode, system_state_t::mode_last, smartie_sorter_t::mot_catcher, smartie_sorter_t::mot_revolver, menu_entry_t::next, lightbarrier_t::passes, menu_entry_t::prev, smartie_sorter_t::prog, prog_color_tcs, prog_none, prog_rotate_catcher, prog_rotate_revolver, prog_set_colors_blue, prog_set_colors_brown, prog_set_colors_green, prog_set_colors_orange, prog_set_colors_pink, prog_set_colors_purple, prog_set_colors_red, prog_set_colors_restore, prog_set_colors_yellow, rotary_encoder_t::push, menu_entry_t::r_action, REFERENCE_MEASURES, smartie_sorter_t::rev, revolver_rotate_relative(), rotary_encoder_t::right, smartie_sorter_t::rotenc, smartie_sorter_t::sens_tcs, sensor_tcs_get_color(), revolver_t::smart, smartie_lcd_write_color(), smartie_sorter_t::speed, stat_finished, stat_idle, stat_start_working, stat_stop_working, stat_working, smartie_sorter_t::state, vibrator_t::status, color_sensor_tcs_t::status, stepper_motor_t::status, vibrator_t::status_last, color_sensor_tcs_t::status_last, stepper_motor_t::status_last, system_state_t::step, sys_get_out_pos(), SYS_MODE_INIT, SYS_MODE_PAUSE, SYS_MODE_RUNNING, stepper_motor_t::target_pos, menu_entry_t::text, ee_memory_t::usr_blu, ee_memory_t::usr_gre, ee_memory_t::usr_red, smartie_sorter_t::vibr, and vibrator_start().