Smarties2: system.h File Reference
system.h File Reference
Smarites machine API header file.
#include <avr/io.h>
Data Structures
struct system_step_t
The single steps during running mode SYS_MODE_RUNNING.
struct system_state_t
Grouping of mode and steps.
struct rotary_encoder_t
The rotary encoder (user input device) structure.
struct smartie_t
Describes the properties a smartie, which is transported by the revolver_t, can have.
struct lightbarrier_t
Describes the module lightbarrier.
struct stepper_motor_t
The stepper motor.
struct color_sensor_adjd_t
Describes the ADJD-S371 color sensor.
struct color_sensor_tcs_t
Describes the TCS230 color sensor.
struct vibrator_t
Describes the virbrator (shaker) module.
struct revolver_t
Describes the revolver module (the disc).
struct smartie_sorter_t
All devices from the smartie sorter collected to one bundle.
Defines
#define COL_SENS_ADJD_LED_PORT PORTA
The ADJD color sensor Port for the LED.
#define COL_SENS_ADJD_LED_BIT PA0
The ADJD color sensor Portbit for the LED.
#define COL_SENS_ADJD_LED_ON (COL_SENS_ADJD_LED_PORT |= (1<<COL_SENS_ADJD_LED_BIT))
Switches the LED of the ADJD color sensor on.
#define COL_SENS_ADJD_LED_OFF (COL_SENS_ADJD_LED_PORT &= ~(1<<COL_SENS_ADJD_LED_BIT))
Switches the LED of the ADJD color sensor off.
#define COL_SENS_TCS_IN_PORT PORTD
Input port for TCS color sensor.
#define COL_SENS_TCS_IN_ICP PD2
ICP pin for TCS color sensor (clock signal).
#define COL_SENS_TCS_OUT_PORT PORTA
Output port for TCS color sensor.
#define COL_SENS_TCS_S2_BIT PA7
S2 settings pin for TCS color sensor.
#define COL_SENS_TCS_S0_BIT PA6
S0 settings pin for TCS color sensor.
#define COL_SENS_TCS_S3_BIT PA5
S3 settings pin for TCS color sensor.
#define COL_SENS_TCS_S1_BIT PA4
S1 settings pin for TCS color sensor.
#define COL_SENS_TCS_OE_BIT PA3
Output Portbit enable for TCS color sensor.
#define COL_SENS_TCS_SAMPLE_TIME 30
Time to measure TCS OUT frequency in milliseconds.
#define COL_SENS_TCS_ENABLE (COL_SENS_TCS_OUT_PORT &= ~(1<<COL_SENS_TCS_OE_BIT))
Enables the TCS color sensor output clk.
#define COL_SENS_TCS_DISABLE (COL_SENS_TCS_OUT_PORT |= (1<<COL_SENS_TCS_OE_BIT))
Disables the TCS color sensor output clk.
#define COL_SENS_TCS_FREQ_MESURE_EN (GICR |= (1<<INT0))
Enables interrupt for counting slopes (falling) from the TCS OUT pin.
#define COL_SENS_TCS_FREQ_MESURE_DI (GICR &= ~(1<<INT0))
Enables interrupt for counting slopes (falling) from the TCS OUT pin.
#define COL_SENS_TCS_SET_FREQ_SCALE(percentage)
Sets the frequency scaler for the TCS color sensor.
#define COL_SENS_TCS_SET_FILTER(color)
Sets the color filter for the TCS color sensor.
#define STEPPER_PORT PORTD
Output port for stepper motors.
#define REV_BIT_EN PD7
Portbit for Enable driver for revolver stepper motor.
#define REV_BIT_CW PD6
Portbit for Rotate direction for revolver stepper motor (CW/CCW).
#define REV_BIT_CLK PD5
Portbit for Clock signal for driver for revolver stepper motor.
#define REV_MOVE_STEP
Move the revolver stepper motor for one single step.
#define REV_ENABLE (STEPPER_PORT |= (1<<REV_BIT_EN))
Enables the driver for the stepper motor.
#define REV_DISABLE (STEPPER_PORT &= ~(1<<REV_BIT_EN))
Disables the driver for the stepper motor.
#define REV_SET_CW (STEPPER_PORT &= ~(1<<REV_BIT_CW))
Rotating direction clockwise.
#define REV_SET_CCW (STEPPER_PORT |= (1<<REV_BIT_CW))
Rotating directino conter clock wise.
#define REV_STEP_DURATION 20
Duration of one step in milliseconds. This value controlles the rotating speed.
#define REV_RAMP_DURATION 1
Duration of the ramp up or ramp down in steps.
#define REV_MAX_SIZE 12
The amount of smarties (holes) which fit into the revolver.
#define REV_STEPS_ESTIMATED 5
Amount of steps for each positions 'hole abouve hole'.
#define CATCH_BIT_EN PD4
Portbit for Enable driver for catcher stepper motor.
#define CATCH_BIT_CW PD1
Portbit for Rotate direction for catcher stepper motor (CW/CC.
#define CATCH_BIT_CLK PD0
Portbit for Clock signal for driver for catcher stepper motorW).
#define CATCH_MOVE_STEP
Move the catcher stepper motor for one single step.
#define CATCH_ENABLE (STEPPER_PORT |= (1<<CATCH_BIT_EN))
Enables the driver for the steper motor.
#define CATCH_DISABLE (STEPPER_PORT &= ~(1<<CATCH_BIT_EN))
Disables the driver for the steper motor.
#define CATCH_SET_CW (STEPPER_PORT &= ~(1<<CATCH_BIT_CW))
Rotating direction clockwise.
#define CATCH_SET_CCW (STEPPER_PORT |= (1<<CATCH_BIT_CW))
Rotating directino conter clock wise.
#define CATCH_STEP_DURATION 10
Duration of one step in one Millisecond. This value controlles the rotating speed.
#define CATCH_RAMP_DURATION 2
Duration of the ramp up or ramp down in steps.
#define CATCH_MAX_SIZE 9
The amount of catcher tubes for sorting the smarties.
#define CATCH_STEPS_ESTIMATED 14
Amount of steps for each positions 'hole abouve hole'.
#define VIBR_PORT PORTB
The Vibrator Port.
#define VIBR_BIT PB3
The Vibrator Portbit.
#define VIBR_ON (VIBR_PORT |= (1<<VIBR_BIT))
Switches the Vibrator on.
#define VIBR_OFF (VIBR_PORT &=~(1<<VIBR_BIT))
Switches the Bibrator off.
#define VIBR_DURATION (700)
Default duration for shaker (vibrator).
#define ROTENC_PORT PORTB
Rotary encoder port (output) for AB signals.
#define ROTENC_A_BIT PB0
Rotary encoder signal A (Pin 5 of connector).
#define ROTENC_B_BIT PB1
Rotary encoder signal B (Pin 4 of connector).
#define ROTENC_PUSH_BIT PB2
Rotary encoder pushbutton signal (Pin 2 of connector).
#define ROTENC_INIT() (ROTENC_DDR &= ~((1<<ROTENC_A_BIT) | (1<<ROTENC_B_BIT) | (1<<ROTENC_PUSH_BIT)))
Initializes input periphals for Rotary encoder.
#define IS_ROTENC_A ((ROTENC_PIN & (1<<ROTENC_A_BIT)))
Output status of rotary encoder.
#define IS_ROTENC_B ((ROTENC_PIN & (1<<ROTENC_B_BIT)))
Output status of rotary encoder.
#define IS_ROTENC_AB (IS_ROTENC_A && IS_ROTENC_B)
Output status of rotary encoder.
#define IS_ROTENC_NONE (!IS_ROTENC_A && !IS_ROTENC_B)
Output status of rotary encoder.
#define IS_ROTENC_PUSH (ROTENC_PIN & (1<<ROTENC_PUSH_BIT))
Output status of rotary encoder.
#define LB_PORT PORTA
Lightbarriere Port.
#define LB_BIT_CATCH PA2
Lightbarriere Catcher Positinoer Portbit.
#define LB_BIT_REV PA1
Lightbarriere Revolver Positioner Portbit.
#define IS_LB_CATCHER (!(LB_PIN & (1<<LB_BIT_CATCH)))
Returns TRUE if lightbarrier is blocked.
#define IS_LB_REVOLVER (!(LB_PIN & (1<<LB_BIT_REV)))
Returns TRUE if lightbarrier is blocked.
Typedefs
typedef float color_avarage [col_unknown]
Stores the color reference values of one channel for all smarties.
Enumerations
enum system_mode_t { SYS_MODE_INIT = 0, SYS_MODE_PAUSE, SYS_MODE_RUNNING }
The mode of the machine.
enum common_stat_t {
stat_idle = 0, stat_start_working, stat_working, stat_stop_working,
stat_finished
}
The status a device can have.
enum program_t {
prog_none = 0, prog_rotate_catcher, prog_rotate_revolver, prog_color_tcs ,
prog_set_colors_blue, prog_set_colors_green, prog_set_colors_red, prog_set_colors_yellow,
prog_set_colors_orange, prog_set_colors_brown, prog_set_colors_purple, prog_set_colors_pink,
prog_set_colors_restore
}
Programs which are executed during SYS_MODE_PAUSE.
enum rotary_encoder_status_t {
ROTENC_NONE = 0, ROTENC_PUSH, ROTENC_A, ROTENC_B,
ROTENC_BOTH
}
The rotary encoder's elements can have following status.
enum smartie_color_t {
col_blue = 0, col_green, col_red, col_yellow,
col_orange, col_brown, col_purple, col_pink,
col_unknown
}
All supported colors.
enum lightbarrier_status_t { lb_free = 0, lb_blocked }
The status a lightbarrier can have.
Functions
void sys_enter_topmenu ()
Will set the current menu to the upper menu layer.
void sys_enter_submenu ()
Will set the current menu to to lower menu layer.
void sys_catcher_enable ()
Enables (power on) the catcher stepper motor.
void sys_catcher_disable ()
Diables (power off) the catcher stepper motor.
void sys_catcher_move_step ()
Moves the catcher stepper motor for on step.
void sys_catcher_rotate ()
Rotates the catcher for one position.
int8_t sys_catcher_is_lb_blocked ()
Returns status for the catcher lightbarrier.
uint8_t sys_get_out_pos ()
Gets the correct out index of the next to drop smartie.
void sys_revolver_move_step ()
Moves the revolver for one step.
void sys_revolver_rotate ()
Rotates the revolver for one position.
int8_t sys_revolver_is_lb_blocked ()
Returns the status for the revolver lightbarrier.
void sys_pause ()
Will Enter the pause mode.
void sys_resume ()
Leave the pause mode.
void sys_reference_measure_blue ()
Initiates color callibration for corresponding smartie color.
void sys_reference_measure_green ()
See sys_reference_measure_blue ().
void sys_reference_measure_red ()
See sys_reference_measure_blue ().
void sys_reference_measure_yellow ()
See sys_reference_measure_blue ().
void sys_reference_measure_orange ()
See sys_reference_measure_blue ().
void sys_reference_measure_brown ()
See sys_reference_measure_blue ().
void sys_reference_measure_pink ()
See sys_reference_measure_blue ().
void sys_reference_measure_purple ()
See sys_reference_measure_blue ().
void sys_reference_measure_restore ()
Initiates to restore the color reference values.
void sys_set_speed ()
Set the operating speed of the sorter to the current demand value.
void sys_speed_up ()
Set the operating speed of the sorter up by decreasing pause times.
void sys_speed_down ()
Set the operating speed of the sorter down by increasing pause times.
void sys_measure_tcs ()
Initiate a color measurement with the tcs color sensor.
void sys_measure_adjd ()
Initiate a color measurement with the adjd color sensor.
void sensor_adjd_get_color ()
Initiates the color detection by the ADJD color sensor.
void sensor_tcs_get_color ()
Initiates the color detection by the TCS color sensor.
void catcher_rotate_absolute (smartie_color move_to)
Rotates the catcher to a certain position.
void catcher_rotate_relative (int8_t)
Rotates the catcher from the current position to a relative next position regarding 'hole above hole'.
void revolver_rotate_relative (int8_t rel_pos)
Rotates the revolver from the current position to a relative next position regarding 'hole above hole'.
void vibrator_start ()
Initiates the vibrator to start.
Detailed Description
Smarites machine API header file.
Copyright (c) 2008 Simeon Felis
GPL2 Licence
Here are many IO related functions declarated
Definition in file system.h.
Define Documentation
#define COL_SENS_TCS_SET_FILTER (color)
Value:
do {                                                        \
        if (color == col_red) {                                 \
            COL_SENS_TCS_OUT_PORT &= ~(1<<COL_SENS_TCS_S2_BIT); \
            COL_SENS_TCS_OUT_PORT &= ~(1<<COL_SENS_TCS_S3_BIT); \
        }                                                       \
        else if (color == col_blue) {                           \
            COL_SENS_TCS_OUT_PORT &= ~(1<<COL_SENS_TCS_S2_BIT); \
            COL_SENS_TCS_OUT_PORT |= (1<<COL_SENS_TCS_S3_BIT);  \
        }                                                       \
        else if (color == col_green) {                          \
            COL_SENS_TCS_OUT_PORT |= (1<<COL_SENS_TCS_S2_BIT);  \
            COL_SENS_TCS_OUT_PORT |= (1<<COL_SENS_TCS_S3_BIT);  \
        }                                                       \
        else if (color == col_unknown) {                        \
            COL_SENS_TCS_OUT_PORT |= (1<<COL_SENS_TCS_S2_BIT);  \
            COL_SENS_TCS_OUT_PORT &= ~(1<<COL_SENS_TCS_S3_BIT); \
        }                                                       \
    } while (0)
Sets the color filter for the TCS color sensor.
Parameters:
color col_red Red filter
col_blue Blue filter
col_green Green filter on
col_unknown No filter
Definition at line 116 of file system.h.
Referenced by sensor_tcs_stuff().
#define COL_SENS_TCS_SET_FREQ_SCALE (percentage)
Value:
do {                                                        \
        COL_SENS_TCS_OUT_PORT &= ~(1<<COL_SENS_TCS_S1_BIT);     \
        COL_SENS_TCS_OUT_PORT &= ~(1<<COL_SENS_TCS_S0_BIT);     \
        if (percentage == 2) {                                  \
            COL_SENS_TCS_OUT_PORT |= (1<<COL_SENS_TCS_S1_BIT);  \
        }                                                       \
        else if (percentage == 20) {                            \
            COL_SENS_TCS_OUT_PORT |= (1<<COL_SENS_TCS_S0_BIT);  \
        }                                                       \
        else if (percentage == 100) {                           \
            COL_SENS_TCS_OUT_PORT |= (1<<COL_SENS_TCS_S0_BIT);  \
            COL_SENS_TCS_OUT_PORT |= (1<<COL_SENS_TCS_S1_BIT);  \
        }                                                       \
    } while (0)
Sets the frequency scaler for the TCS color sensor.
Parameters:
percentage 2 2%
20 20%
100 100%
Definition at line 92 of file system.h.
Referenced by init_sensor_tcs().
Enumeration Type Documentation
enum common_stat_t
The status a device can have.
The different modules of the smartie sorter can have different operating status. You can recognize if a module has just finished by checking the last status.
Enumerator:
stat_idle The module/device is doing nothing and is ready for a new job.
stat_start_working Setting a module's state to this will start the device to work.
stat_working Indicates the device is busy. The device will automatically change to this state.
stat_stop_working Setting a device to this state will stop the device.
stat_finished Indicates the device is finished. The device will automatically change to this state.
Definition at line 252 of file system.h.
enum lightbarrier_status_t
The status a lightbarrier can have.
Enumerator:
lb_free Nothing inbetween the lightbarrier.
lb_blocked The lightbarrier is blocked.
Definition at line 354 of file system.h.
enum program_t
Programs which are executed during SYS_MODE_PAUSE.
Enumerator:
prog_none No program executed.
prog_rotate_catcher Indicates that the catcher rotate program is running.
prog_rotate_revolver Indicates that the revolver rotate program is running.
prog_color_tcs Indicates that the color measure program is runnging.
prog_set_colors_blue Calibrates the color refence values. Halts the state machine.
prog_set_colors_green Calibrates the color refence values. Halts the state machine.
prog_set_colors_red Calibrates the color refence values. Halts the state machine.
prog_set_colors_yellow Calibrates the color refence values. Halts the state machine.
prog_set_colors_orange Calibrates the color refence values. Halts the state machine.
prog_set_colors_brown Calibrates the color refence values. Halts the state machine.
prog_set_colors_purple Calibrates the color refence values. Halts the state machine.
prog_set_colors_pink Calibrates the color refence values. Halts the state machine.
prog_set_colors_restore Resores the color refernce values to system defaults. Halts the state machine.
Definition at line 281 of file system.h.
enum rotary_encoder_status_t
The rotary encoder's elements can have following status.
Enumerator:
ROTENC_NONE Applicable for Push button, A-Pin and B-Pin.
ROTENC_PUSH The Button is pushed.
ROTENC_A Currently only the A-Pin of the rotary encoder is set.
ROTENC_B Currently only the B-Pin of the rotary encoder is set.
ROTENC_BOTH Currently both, the A-Pin and B-Pin of the rotary encoder are set.
Definition at line 302 of file system.h.
enum smartie_color_t
All supported colors.
This enum is used for indexing the reference color tables, the positioning of the catcher and may be more. col_unknown is often used as end conditions for loops. In the color tables, this enums elements represent the index for color rows.
Enumerator:
col_blue Blue.
col_green Green.
col_red Red.
col_yellow Yellow.
col_orange Orange.
col_brown Brown.
col_purple Purple.
col_pink Pink.
col_unknown Indexed as last color (highest counter). Insert colors above this one!
Definition at line 329 of file system.h.
enum system_mode_t
The mode of the machine.
Enumerator:
SYS_MODE_INIT After reset or power on.
SYS_MODE_PAUSE Pausing the smartie sorter and operated manually.
SYS_MODE_RUNNING Smartie sorter is running automatically.
Definition at line 239 of file system.h.
Function Documentation
void catcher_rotate_absolute (smartie_color move_to)
Rotates the catcher to a certain position.
This function will rotate the catcher to position specified by the a color smartie_color_t.
Definition at line 346 of file system.c.
References CATCH_MAX_SIZE, catcher_rotate_relative(), col_unknown, stepper_motor_t::current_pos, smartie_sorter_t::mot_catcher, stat_finished, and stepper_motor_t::status_last.
Referenced by main().
void catcher_rotate_relative (int8_t rel_pos)
Rotates the catcher from the current position to a relative next position regarding 'hole above hole'.
Most of the work is being done in motor_stuff.
Warning: This function does not check if the catcher is already working. Before calling this function, check if the motor's status and last status equals stat_idle. It also doesn't check the parameter, if the value is reasonable.
Parameters:
rel_pos The position where to move to. The value of rel_pos will be not checked, so the value must be lower than REV_MAX_SIZE or CATCH_MAX_SIZE.
Definition at line 384 of file system.c.
References CATCH_MAX_SIZE, stepper_motor_t::current_pos, smartie_sorter_t::mot_catcher, stat_finished, stat_start_working, stepper_motor_t::status, stepper_motor_t::status_last, and stepper_motor_t::target_pos.
Referenced by catcher_rotate_absolute(), init_motors(), and sys_catcher_rotate().
void revolver_rotate_relative (int8_t rel_pos)
Rotates the revolver from the current position to a relative next position regarding 'hole above hole'.
Most of the work is being done in motor_stuff.
Warning: This function does not check if the revolver is already working. Before calling this function, check if the motor's status and last status equals stat_idle. It also doesn't check the parameter, if the value is reasonable.
Parameters:
rel_pos The position where to move to. The value of rel_pos will be not checked, so the value must be lower than REV_MAX_SIZE or CATCH_MAX_SIZE.
Definition at line 415 of file system.c.
References stepper_motor_t::current_pos, smartie_sorter_t::mot_revolver, REV_MAX_SIZE, stat_finished, stat_start_working, stepper_motor_t::status, stepper_motor_t::status_last, and stepper_motor_t::target_pos.
Referenced by init_motors(), main(), and sys_revolver_rotate().
void sys_catcher_disable ()
Diables (power off) the catcher stepper motor.
This function is prepared especially for functions started from the menu. This function works only if the menu is correct initialized.
Definition at line 44 of file system.c.
References CATCH_DISABLE.
Referenced by init_motors().
void sys_catcher_enable ()
Enables (power on) the catcher stepper motor.
This function is prepared especially for functions started from the menu. This function works only if the menu is correct initialized.
Definition at line 54 of file system.c.
References CATCH_ENABLE.
Referenced by init_motors().
int8_t sys_catcher_is_lb_blocked ()
Returns status for the catcher lightbarrier.
This function is prepared especially for functions started from the menu. This function works only if the menu is correct initialized.
Definition at line 98 of file system.c.
References IS_LB_CATCHER.
Referenced by init_motors().
void sys_catcher_rotate ()
Rotates the catcher for one position.
This function is intened for manual usage and should not be used during normal running mode SYS_MODE_RUNNING, only during SYS_MODE_PAUSE.
Definition at line 72 of file system.c.
References catcher_rotate_relative(), smartie_sorter_t::mot_catcher, smartie_sorter_t::prog, prog_rotate_catcher, stat_idle, stepper_motor_t::status, and stepper_motor_t::status_last.
Referenced by init_menu().
void sys_enter_submenu ()
Will set the current menu to to lower menu layer.
This function is prepared especially for functions started from the menu. This function works only if the menu is correct initialized.
Definition at line 33 of file system.c.
References smartie_sorter_t::prog, prog_none, and menu_entry_t::submenu.
Referenced by init_menu().
void sys_enter_topmenu ()
Will set the current menu to the upper menu layer.
This function is prepared especially for functions started from the menu. This function works only if the menu is correct initialized.
Definition at line 22 of file system.c.
References smartie_sorter_t::prog, prog_none, and menu_entry_t::topmenu.
Referenced by init_menu().
uint8_t sys_get_out_pos ()
Gets the correct out index of the next to drop smartie.
Returns:
The index of smartie in the revolver which will be dropped next
Definition at line 85 of file system.c.
References stepper_motor_t::current_pos, smartie_sorter_t::mot_revolver, and REV_MAX_SIZE.
Referenced by main().
void sys_pause ()
Will Enter the pause mode.
This function will enter the pause mode after the current function is finished. This function is usually called from the lcd menu. This function is only available in the mode SYS_MODE_RUNNING
Definition at line 149 of file system.c.
References system_state_t::mode, system_state_t::mode_last, smartie_sorter_t::state, and SYS_MODE_PAUSE.
Referenced by init_menu().
void sys_reference_measure_blue ()
Initiates color callibration for corresponding smartie color.
This function is prepared especially for functions started from the menu. This function works only if the menu is correct initialized.
Definition at line 163 of file system.c.
References smartie_sorter_t::prog, and prog_set_colors_blue.
Referenced by init_menu().
void sys_reference_measure_restore ()
Initiates to restore the color reference values.
This function is prepared especially for functions started from the menu. This function works only if the menu is correct initialized.
Definition at line 222 of file system.c.
References smartie_sorter_t::prog, and prog_set_colors_restore.
Referenced by init_menu().
void sys_resume ()
Leave the pause mode.
This function will leave the pause mode. This function is usually called from the lcd menu. This function is only available in the mode SYS_MODE_PAUSE
Definition at line 233 of file system.c.
References system_state_t::mode, system_state_t::mode_last, smartie_sorter_t::state, and SYS_MODE_RUNNING.
Referenced by init_menu().
int8_t sys_revolver_is_lb_blocked ()
Returns the status for the revolver lightbarrier.
This function is prepared especially for functions started from the menu. This function works only if the menu is correct initialized.
Definition at line 138 of file system.c.
References IS_LB_REVOLVER.
Referenced by init_motors().
void sys_revolver_rotate ()
Rotates the revolver for one position.
This function is intened for manual usage and should not be used during normal running mode SYS_MODE_RUNNING, only during SYS_MODE_PAUSE.
Definition at line 118 of file system.c.
References smartie_sorter_t::mot_revolver, smartie_sorter_t::prog, prog_rotate_revolver, revolver_rotate_relative(), stat_idle, stepper_motor_t::status, and stepper_motor_t::status_last.
Referenced by init_menu().
void sys_speed_down ()
Set the operating speed of the sorter down by increasing pause times.
This function is prepared especially for functions started from the menu. This function works only if the menu is correct initialized.
Definition at line 269 of file system.c.
References smartie_sorter_t::prog, smartie_sorter_t::speed, and sys_set_speed().
Referenced by init_menu().
void sys_speed_up ()
Set the operating speed of the sorter up by decreasing pause times.
This function is prepared especially for functions started from the menu. This function works only if the menu is correct initialized.
Definition at line 256 of file system.c.
References smartie_sorter_t::prog, smartie_sorter_t::speed, and sys_set_speed().
Referenced by init_menu().