Smarties2: system.c File Reference
system.c File Reference
Short routines for controlling the whole system and modules.
#include <avr/eeprom.h>
#include "system.h"
#include "menu.h"
Functions
void sys_enter_topmenu ()
Will set the current menu to the upper menu layer.
void sys_enter_submenu ()
Will set the current menu to to lower menu layer.
void sys_catcher_disable ()
Diables (power off) the catcher stepper motor.
void sys_catcher_enable ()
Enables (power on) the catcher stepper motor.
void sys_catcher_move_step ()
Moves the catcher stepper motor for on step.
void sys_catcher_rotate ()
Rotates the catcher for one position.
uint8_t sys_get_out_pos ()
Gets the correct out index of the next to drop smartie.
int8_t sys_catcher_is_lb_blocked ()
Returns status for the catcher lightbarrier.
void sys_revolver_rotate ()
Rotates the revolver for one position.
void sys_revolver_move_step ()
Moves the revolver for one step.
int8_t sys_revolver_is_lb_blocked ()
Returns the status for the revolver lightbarrier.
void sys_pause ()
Will Enter the pause mode.
void sys_reference_measure_blue ()
Initiates color callibration for corresponding smartie color.
void sys_reference_measure_green ()
See sys_reference_measure_blue ().
void sys_reference_measure_red ()
See sys_reference_measure_blue ().
void sys_reference_measure_yellow ()
See sys_reference_measure_blue ().
void sys_reference_measure_orange ()
See sys_reference_measure_blue ().
void sys_reference_measure_brown ()
See sys_reference_measure_blue ().
void sys_reference_measure_purple ()
See sys_reference_measure_blue ().
void sys_reference_measure_pink ()
See sys_reference_measure_blue ().
void sys_reference_measure_restore ()
Initiates to restore the color reference values.
void sys_resume ()
Leave the pause mode.
void sys_set_speed ()
Set the operating speed of the sorter to the current demand value.
void sys_speed_up ()
Set the operating speed of the sorter up by decreasing pause times.
void sys_speed_down ()
Set the operating speed of the sorter down by increasing pause times.
void sys_measure_tcs ()
Initiate a color measurement with the tcs color sensor.
void sys_measure_adjd ()
Initiate a color measurement with the adjd color sensor.
void vibrator_start ()
Initiates the vibrator to start.
void sensor_adjd_get_color ()
Initiates the color detection by the ADJD color sensor.
void sensor_tcs_get_color ()
Initiates the color detection by the TCS color sensor.
void catcher_rotate_absolute (smartie_color move_to)
Rotates the catcher to a certain position.
void catcher_rotate_relative (int8_t rel_pos)
Rotates the catcher from the current position to a relative next position regarding 'hole above hole'.
void revolver_rotate_relative (int8_t rel_pos)
Rotates the revolver from the current position to a relative next position regarding 'hole above hole'.
Detailed Description
Short routines for controlling the whole system and modules.
Definition in file system.c.
Function Documentation
void catcher_rotate_absolute (smartie_color move_to)
Rotates the catcher to a certain position.
This function will rotate the catcher to position specified by the a color smartie_color_t.
Definition at line 346 of file system.c.
References CATCH_MAX_SIZE, catcher_rotate_relative(), col_unknown, stepper_motor_t::current_pos, smartie_sorter_t::mot_catcher, stat_finished, and stepper_motor_t::status_last.
Referenced by main().
void catcher_rotate_relative (int8_t rel_pos)
Rotates the catcher from the current position to a relative next position regarding 'hole above hole'.
Most of the work is being done in motor_stuff.
Warning: This function does not check if the catcher is already working. Before calling this function, check if the motor's status and last status equals stat_idle. It also doesn't check the parameter, if the value is reasonable.
Parameters:
rel_pos The position where to move to. The value of rel_pos will be not checked, so the value must be lower than REV_MAX_SIZE or CATCH_MAX_SIZE.
Definition at line 384 of file system.c.
References CATCH_MAX_SIZE, stepper_motor_t::current_pos, smartie_sorter_t::mot_catcher, stat_finished, stat_start_working, stepper_motor_t::status, stepper_motor_t::status_last, and stepper_motor_t::target_pos.
Referenced by catcher_rotate_absolute(), init_motors(), and sys_catcher_rotate().
void revolver_rotate_relative (int8_t rel_pos)
Rotates the revolver from the current position to a relative next position regarding 'hole above hole'.
Most of the work is being done in motor_stuff.
Warning: This function does not check if the revolver is already working. Before calling this function, check if the motor's status and last status equals stat_idle. It also doesn't check the parameter, if the value is reasonable.
Parameters:
rel_pos The position where to move to. The value of rel_pos will be not checked, so the value must be lower than REV_MAX_SIZE or CATCH_MAX_SIZE.
Definition at line 415 of file system.c.
References stepper_motor_t::current_pos, smartie_sorter_t::mot_revolver, REV_MAX_SIZE, stat_finished, stat_start_working, stepper_motor_t::status, stepper_motor_t::status_last, and stepper_motor_t::target_pos.
Referenced by init_motors(), main(), and sys_revolver_rotate().
void sys_catcher_disable ()
Diables (power off) the catcher stepper motor.
This function is prepared especially for functions started from the menu. This function works only if the menu is correct initialized.
Definition at line 44 of file system.c.
References CATCH_DISABLE.
Referenced by init_motors().
void sys_catcher_enable ()
Enables (power on) the catcher stepper motor.
This function is prepared especially for functions started from the menu. This function works only if the menu is correct initialized.
Definition at line 54 of file system.c.
References CATCH_ENABLE.
Referenced by init_motors().
int8_t sys_catcher_is_lb_blocked ()
Returns status for the catcher lightbarrier.
This function is prepared especially for functions started from the menu. This function works only if the menu is correct initialized.
Definition at line 98 of file system.c.
References IS_LB_CATCHER.
Referenced by init_motors().
void sys_catcher_rotate ()
Rotates the catcher for one position.
This function is intened for manual usage and should not be used during normal running mode SYS_MODE_RUNNING, only during SYS_MODE_PAUSE.
Definition at line 72 of file system.c.
References catcher_rotate_relative(), smartie_sorter_t::mot_catcher, smartie_sorter_t::prog, prog_rotate_catcher, stat_idle, stepper_motor_t::status, and stepper_motor_t::status_last.
Referenced by init_menu().
void sys_enter_submenu ()
Will set the current menu to to lower menu layer.
This function is prepared especially for functions started from the menu. This function works only if the menu is correct initialized.
Definition at line 33 of file system.c.
References smartie_sorter_t::prog, prog_none, and menu_entry_t::submenu.
Referenced by init_menu().
void sys_enter_topmenu ()
Will set the current menu to the upper menu layer.
This function is prepared especially for functions started from the menu. This function works only if the menu is correct initialized.
Definition at line 22 of file system.c.
References smartie_sorter_t::prog, prog_none, and menu_entry_t::topmenu.
Referenced by init_menu().
uint8_t sys_get_out_pos ()
Gets the correct out index of the next to drop smartie.
Returns:
The index of smartie in the revolver which will be dropped next
Definition at line 85 of file system.c.
References stepper_motor_t::current_pos, smartie_sorter_t::mot_revolver, and REV_MAX_SIZE.
Referenced by main().
void sys_pause ()
Will Enter the pause mode.
This function will enter the pause mode after the current function is finished. This function is usually called from the lcd menu. This function is only available in the mode SYS_MODE_RUNNING
Definition at line 149 of file system.c.
References system_state_t::mode, system_state_t::mode_last, smartie_sorter_t::state, and SYS_MODE_PAUSE.
Referenced by init_menu().
void sys_reference_measure_blue ()
Initiates color callibration for corresponding smartie color.
This function is prepared especially for functions started from the menu. This function works only if the menu is correct initialized.
Definition at line 163 of file system.c.
References smartie_sorter_t::prog, and prog_set_colors_blue.
Referenced by init_menu().
void sys_reference_measure_restore ()
Initiates to restore the color reference values.
This function is prepared especially for functions started from the menu. This function works only if the menu is correct initialized.
Definition at line 222 of file system.c.
References smartie_sorter_t::prog, and prog_set_colors_restore.
Referenced by init_menu().
void sys_resume ()
Leave the pause mode.
This function will leave the pause mode. This function is usually called from the lcd menu. This function is only available in the mode SYS_MODE_PAUSE
Definition at line 233 of file system.c.
References system_state_t::mode, system_state_t::mode_last, smartie_sorter_t::state, and SYS_MODE_RUNNING.
Referenced by init_menu().
int8_t sys_revolver_is_lb_blocked ()
Returns the status for the revolver lightbarrier.
This function is prepared especially for functions started from the menu. This function works only if the menu is correct initialized.
Definition at line 138 of file system.c.
References IS_LB_REVOLVER.
Referenced by init_motors().
void sys_revolver_rotate ()
Rotates the revolver for one position.
This function is intened for manual usage and should not be used during normal running mode SYS_MODE_RUNNING, only during SYS_MODE_PAUSE.
Definition at line 118 of file system.c.
References smartie_sorter_t::mot_revolver, smartie_sorter_t::prog, prog_rotate_revolver, revolver_rotate_relative(), stat_idle, stepper_motor_t::status, and stepper_motor_t::status_last.
Referenced by init_menu().
void sys_speed_down ()
Set the operating speed of the sorter down by increasing pause times.
This function is prepared especially for functions started from the menu. This function works only if the menu is correct initialized.
Definition at line 269 of file system.c.
References smartie_sorter_t::prog, smartie_sorter_t::speed, and sys_set_speed().
Referenced by init_menu().
void sys_speed_up ()
Set the operating speed of the sorter up by decreasing pause times.
This function is prepared especially for functions started from the menu. This function works only if the menu is correct initialized.
Definition at line 256 of file system.c.
References smartie_sorter_t::prog, smartie_sorter_t::speed, and sys_set_speed().
Referenced by init_menu().